# Generated by Django 4.1 on 2023-09-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timescales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('century', models.CharField(max_length=50)),
                ('decade', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=50)),
                ('minute', models.CharField(max_length=50)),
                ('second', models.CharField(max_length=50)),
            ],
        ),
    ]
