# Generated by Django 4.1 on 2023-09-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qipu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_request_date', models.DateTimeField()),
                ('in_request_date', models.DateTimeField()),
                ('invite_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('recurrence_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qipu_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('caption', models.CharField(max_length=50)),
                ('media_type', models.CharField(max_length=50)),
                ('permalink', models.CharField(max_length=50)),
                ('shortcode', models.CharField(max_length=50)),
                ('storage_file', models.FileField(storage='default_storage', upload_to='your-upload-path/')),
                ('is_published', models.BooleanField()),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='timescales',
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qipu_app.user'),
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qipu_app.user'),
        ),
        migrations.AddField(
            model_name='contacter',
            name='contacted_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qipu_app.user'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qipu_app.event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qipu_app.user'),
        ),
    ]
