# Generated by Django 4.1 on 2023-09-13 20:37

from django.db import migrations, models
import django.db.models.deletion
import qipu_app.utility


class Migration(migrations.Migration):

    dependencies = [
        ('qipu_app', '0002_attendee_contacter_event_media_post_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='storage_file',
            field=models.FileField(upload_to=qipu_app.utility.media_file_upload),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qipu_app.attendee')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qipu_app.contacter')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qipu_app.event')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qipu_app.media')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qipu_app.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qipu_app.user')),
            ],
        ),
    ]
